server {
    listen 80;

    resolver 127.0.0.11 valid=30s;

    location / {
        set $upstream_front frontend;
        proxy_pass http://$upstream_front:5173;
        proxy_set_header Host $host;
    }

    location /api/users {
        set $upstream_user user-service;
        proxy_pass http://$upstream_user:8081;
        proxy_set_header Host $host;
    }

    location /api/questions {
        set $upstream_ques question-service;
        proxy_pass http://$upstream_ques:8080;
        proxy_set_header Host $host;
    }

    location /api/matches {
        set $upstream_match matching-service;
        proxy_pass http://$upstream_match:8082;
        proxy_set_header Host $host;
    }

    location /api/collab/ {
        set $upstream_collab collaboration-service;
        rewrite ^/api/collab/sessions/(.*)$ /api/sessions/$1 break;
        rewrite ^/api/collab/(.*)$ /api/sessions/$1 break;
        proxy_pass http://$upstream_collab:8083;
        proxy_set_header Host $host;
    }


    location /ws/matches {
        set $upstream_ws_match matching-service;
        proxy_pass http://$upstream_ws_match:8082;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

location /ws/sessions/ {
    set $upstream_ws_sess collaboration-service;
    proxy_pass http://$upstream_ws_sess:8083; 
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}

    location /ws/chat/ {
        set $upstream_ws_chat collaboration-service;
        proxy_pass http://$upstream_ws_chat:8083;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}